### ISSUE TITLE
Support external style and/or className

### ISSUE THREAD

**Issue by Hypnosphi** [skratchdot/react-github-corner#45]
Now I have to wrap it in an extra div to apply styling =(

**Comment by skratchdot** [comment]
That makes sense. I'll try to update this lib soon.  I haven't touched it in a long time.

**Comment by skratchdot** [comment]
Probably makes sense for me to start using inline styles as well.  I'll try to update this line soon:

https://github.com/skratchdot/react-github-corner/blob/master/src/lib/GithubCorner.js#L58

**Comment by Hypnosphi** [comment]
You can't do `:hover` with inline styles

**Comment by skratchdot** [comment]
true, but I could use 'onmouse*' events, etc.  was just thinking about using a css-in-js solution (like glamorous etc), but perhaps that big of change isn't worth it.

**Comment by skratchdot** [comment]
after re-looking at https://github.com/skratchdot/react-github-corner/blob/master/src/lib/styles.js it's probably best not to make any changes (to keep this lib small).  I should easily be able to add `...props` to the main component though (so users can pass in additional properties).

**Comment by Hypnosphi** [comment]
Just don't forget to join external classname with your own =)

**Comment by skratchdot** [comment]
@Hypnosphi - I just published `1.0.0` with this fix.  Please try it out and let me know if it works!
